[package]
name = "ublox"
version = "0.1.0"
authors = ["Lane Kolbly <lane@rscheme.org>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serialport = "3.3.0"
bincode = "1.1.4"
chrono = "0.4"
crc = "1.8.1"
