[package]
name = "ublox_derive"
version = "0.0.0"
authors = ["Lane Kolbly <lane@rscheme.org>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0.14", features = ["extra-traits"] }
Inflector = "0.11.4"
proc-macro-error = "0.4.8"
itertools = "0.8.2"
num-traits = "0.2"
num-derive = "0.2"
